"""empty message

Revision ID: 22c6c68a027f
Revises: 280e7687ca87
Create Date: 2017-10-26 16:47:42.102852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c6c68a027f'
down_revision = '280e7687ca87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('warblers_username_fkey', 'warblers', type_='foreignkey')
    op.drop_column('warblers', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warblers', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('warblers_username_fkey', 'warblers', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
