"""empty message

Revision ID: 8706b55bc460
Revises: 22c6c68a027f
Create Date: 2017-11-06 17:34:42.188134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8706b55bc460'
down_revision = '22c6c68a027f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.Text(), nullable=True))
    op.add_column('warblers', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warblers', 'img_url')
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###
